import swaggerJsdoc from 'swagger-jsdoc';
import path from 'path';

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: '3.0.3',
    info: {
      title: 'SIGAH API',
      version: '1.0.0',
      description:
        'Sistema de Información para Gestión de Ayuda Humanitaria — Montería. ' +
        'API REST para registrar, priorizar y distribuir ayuda humanitaria a familias damnificadas.',
      contact: {
        name: 'Equipo SIGAH',
      },
    },
    servers: [
      {
        url: 'http://localhost:3000/api/v1',
        description: 'Local',
      },
    ],
    tags: [
      { name: 'Auth', description: 'Autenticación y gestión de usuarios' },
      { name: 'Zones', description: 'Zonas geográficas de riesgo' },
      { name: 'Shelters', description: 'Refugios y albergues' },
      { name: 'Families', description: 'Registro de familias damnificadas' },
      { name: 'Persons', description: 'Personas integrantes de familias' },
      { name: 'Warehouses', description: 'Bodegas de almacenamiento' },
      { name: 'ResourceTypes', description: 'Tipos de recursos humanitarios' },
      { name: 'Inventory', description: 'Inventario en bodegas' },
      { name: 'AlertThresholds', description: 'Umbrales de alerta de inventario' },
      { name: 'Donors', description: 'Donantes' },
      { name: 'Donations', description: 'Registro de donaciones' },
      { name: 'ScoringConfig', description: 'Configuración de pesos de priorización' },
      { name: 'Prioritization', description: 'Ranking y lotes de priorización' },
      { name: 'Deliveries', description: 'Entregas de ayuda humanitaria' },
      { name: 'DistributionPlans', description: 'Planes de distribución' },
      { name: 'HealthVectors', description: 'Vectores de riesgo sanitario' },
      { name: 'Relocations', description: 'Reubicaciones de familias entre refugios' },
      { name: 'AuditLogs', description: 'Log de auditoría inmutable' },
      { name: 'Map', description: 'Datos geoespaciales para mapa' },
      { name: 'Reports', description: 'Reportes y dashboard de métricas' },
      { name: 'Sync', description: 'Sincronización offline' },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'Token JWT obtenido en POST /auth/login',
        },
      },
      parameters: {
        PageParam: {
          in: 'query',
          name: 'page',
          schema: { type: 'integer', minimum: 1, default: 1 },
          required: false,
          description: 'Número de página (base 1)',
        },
        LimitParam: {
          in: 'query',
          name: 'limit',
          schema: { type: 'integer', minimum: 1, maximum: 200, default: 20 },
          required: false,
          description: 'Registros por página',
        },
        IdParam: {
          in: 'path',
          name: 'id',
          schema: { type: 'integer', minimum: 1 },
          required: true,
          description: 'ID numérico del recurso',
        },
      },
      schemas: {
        // ── Auxiliares ──────────────────────────────────────────────────
        ErrorResponse: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: false },
            error: { type: 'string', example: 'Mensaje de error' },
          },
          required: ['success', 'error'],
        },
        PaginationMeta: {
          type: 'object',
          properties: {
            page: { type: 'integer', example: 1 },
            limit: { type: 'integer', example: 20 },
            total: { type: 'integer', example: 100 },
            totalPages: { type: 'integer', example: 5 },
          },
          required: ['page', 'limit', 'total', 'totalPages'],
        },
        SuccessResponse: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: true },
            data: {},
            message: { type: 'string' },
            pagination: { $ref: '#/components/schemas/PaginationMeta' },
          },
          required: ['success'],
        },
        // ── Entidades principales ────────────────────────────────────────
        User: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            email: { type: 'string', format: 'email' },
            role: {
              type: 'string',
              enum: [
                'ADMIN',
                'CENSADOR',
                'OPERADOR_ENTREGAS',
                'COORDINADOR_LOGISTICA',
                'FUNCIONARIO_CONTROL',
                'REGISTRADOR_DONACIONES',
              ],
            },
            name: { type: 'string' },
            is_active: { type: 'boolean' },
            failed_login_attempts: { type: 'integer' },
            locked_until: { type: 'string', format: 'date-time', nullable: true },
            last_login_at: { type: 'string', format: 'date-time', nullable: true },
            password_must_change: { type: 'boolean' },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        Zone: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            name: { type: 'string' },
            risk_level: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] },
            latitude: { type: 'number', format: 'double' },
            longitude: { type: 'number', format: 'double' },
            estimated_population: { type: 'integer' },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        Shelter: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            name: { type: 'string' },
            address: { type: 'string' },
            zone_id: { type: 'integer' },
            max_capacity: { type: 'integer' },
            current_occupancy: { type: 'integer' },
            type: {
              type: 'string',
              enum: ['SCHOOL', 'CHURCH', 'COMMUNITY_CENTER', 'STADIUM', 'TENT', 'OTHER'],
            },
            latitude: { type: 'number', format: 'double' },
            longitude: { type: 'number', format: 'double' },
            is_over_capacity: { type: 'boolean' },
            occupancy_ratio: { type: 'number', nullable: true },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        Family: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            family_code: { type: 'string' },
            head_document: { type: 'string' },
            zone_id: { type: 'integer' },
            shelter_id: { type: 'integer', nullable: true },
            num_members: { type: 'integer' },
            num_children_under_5: { type: 'integer' },
            num_adults_over_65: { type: 'integer' },
            num_pregnant: { type: 'integer' },
            num_disabled: { type: 'integer' },
            priority_score: { type: 'number' },
            priority_score_breakdown: { type: 'object' },
            status: { type: 'string', enum: ['ACTIVO', 'EN_REFUGIO', 'EVACUADO'] },
            latitude: { type: 'number', nullable: true },
            longitude: { type: 'number', nullable: true },
            reference_address: { type: 'string', nullable: true },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        Person: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            family_id: { type: 'integer' },
            name: { type: 'string' },
            document: { type: 'string' },
            birth_date: { type: 'string', format: 'date' },
            gender: { type: 'string', enum: ['M', 'F', 'OTRO'] },
            relationship: {
              type: 'string',
              enum: ['ESPOSO_A', 'HIJO_A', 'PADRE_MADRE', 'HERMANO_A', 'OTRO'],
            },
            special_conditions: {
              type: 'array',
              items: {
                type: 'string',
                enum: ['CHILD_UNDER_5', 'ELDERLY_OVER_65', 'PREGNANT', 'DISABLED'],
              },
            },
            requires_medication: { type: 'boolean' },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        Warehouse: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            name: { type: 'string' },
            address: { type: 'string' },
            zone_id: { type: 'integer' },
            max_capacity_kg: { type: 'number' },
            current_weight_kg: { type: 'number' },
            status: { type: 'string', enum: ['ACTIVE', 'INACTIVE'] },
            latitude: { type: 'number', format: 'double' },
            longitude: { type: 'number', format: 'double' },
            is_over_85_percent: { type: 'boolean' },
            occupancy_ratio: { type: 'number', nullable: true },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        ResourceType: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            name: { type: 'string' },
            category: {
              type: 'string',
              enum: ['FOOD', 'BLANKET', 'MATTRESS', 'HYGIENE', 'MEDICATION'],
            },
            unit_of_measure: { type: 'string' },
            unit_weight_kg: { type: 'number' },
            is_active: { type: 'boolean' },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        InventoryRow: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            warehouse_id: { type: 'integer' },
            resource_type_id: { type: 'integer' },
            available_quantity: { type: 'number' },
            total_weight_kg: { type: 'number' },
            batch: { type: 'string' },
            expiration_date: { type: 'string', format: 'date', nullable: true },
            is_expired: { type: 'boolean' },
            resource: { $ref: '#/components/schemas/ResourceType' },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        AlertThreshold: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            resource_type_id: { type: 'integer' },
            min_quantity: { type: 'number' },
            updated_by: { type: 'integer', nullable: true },
            updated_at: { type: 'string', format: 'date-time' },
            resource: { $ref: '#/components/schemas/ResourceType' },
          },
        },
        InventoryAlert: {
          type: 'object',
          properties: {
            kind: {
              type: 'string',
              enum: ['LOW_STOCK', 'EXPIRING_SOON', 'EXPIRED', 'WAREHOUSE_OVER_85'],
            },
            severity: { type: 'string', enum: ['CRITICAL', 'HIGH', 'MEDIUM'] },
            message: { type: 'string' },
            link: { type: 'string' },
            metadata: { type: 'object' },
          },
        },
        Donor: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            name: { type: 'string' },
            type: {
              type: 'string',
              enum: [
                'PERSONA_NATURAL',
                'EMPRESA',
                'ALCALDIA',
                'GOBERNACION',
                'ORGANIZACION',
              ],
            },
            contact: { type: 'string' },
            tax_id: { type: 'string', nullable: true },
            is_active: { type: 'boolean' },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        DonationDetail: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            resource_type_id: { type: 'integer' },
            resource_name: { type: 'string' },
            category: {
              type: 'string',
              enum: ['FOOD', 'BLANKET', 'MATTRESS', 'HYGIENE', 'MEDICATION'],
            },
            quantity: { type: 'number' },
            weight_kg: { type: 'number' },
            batch: { type: 'string', nullable: true },
            expiration_date: { type: 'string', format: 'date', nullable: true },
          },
        },
        Donation: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            donation_code: { type: 'string' },
            donor_id: { type: 'integer' },
            destination_warehouse_id: { type: 'integer', nullable: true },
            donation_type: { type: 'string', enum: ['IN_KIND', 'MONETARY', 'MIXED'] },
            monetary_amount: { type: 'string', nullable: true },
            date: { type: 'string', format: 'date-time' },
            notes: { type: 'string', nullable: true },
            created_by: { type: 'integer', nullable: true },
            details: {
              type: 'array',
              items: { $ref: '#/components/schemas/DonationDetail' },
            },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        ScoringConfigRow: {
          type: 'object',
          properties: {
            key: {
              type: 'string',
              enum: [
                'W_MEMBERS',
                'W_CHILDREN_5',
                'W_ADULTS_65',
                'W_PREGNANT',
                'W_DISABLED',
                'W_ZONE_RISK',
                'W_DAYS_NO_AID',
                'W_DELIVERIES',
                'MAX_DAYS',
              ],
            },
            value: { type: 'number' },
            updated_by: { type: 'integer', nullable: true },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        RankingRow: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            family_code: { type: 'string' },
            head_document: { type: 'string' },
            zone_id: { type: 'integer' },
            zone_name: { type: 'string' },
            shelter_id: { type: 'integer', nullable: true },
            num_members: { type: 'integer' },
            num_children_under_5: { type: 'integer' },
            num_adults_over_65: { type: 'integer' },
            num_pregnant: { type: 'integer' },
            num_disabled: { type: 'integer' },
            priority_score: { type: 'number' },
            priority_score_breakdown: { type: 'object' },
            status: { type: 'string', enum: ['ACTIVO', 'EN_REFUGIO', 'EVACUADO'] },
            last_delivery_date: { type: 'string', format: 'date', nullable: true },
          },
        },
        DeliveryDetail: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            resource_type_id: { type: 'integer' },
            resource_name: { type: 'string' },
            category: {
              type: 'string',
              enum: ['FOOD', 'BLANKET', 'MATTRESS', 'HYGIENE', 'MEDICATION'],
            },
            quantity: { type: 'number' },
            weight_kg: { type: 'number' },
            batch: { type: 'string', nullable: true },
          },
        },
        Delivery: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            delivery_code: { type: 'string' },
            family_id: { type: 'integer' },
            source_warehouse_id: { type: 'integer' },
            plan_item_id: { type: 'integer', nullable: true },
            delivery_date: { type: 'string', format: 'date-time' },
            delivered_by: { type: 'integer', nullable: true },
            received_by_document: { type: 'string', nullable: true },
            coverage_days: { type: 'integer', minimum: 3 },
            status: { type: 'string', enum: ['PROGRAMADA', 'EN_CURSO', 'ENTREGADA'] },
            delivery_latitude: { type: 'number', nullable: true },
            delivery_longitude: { type: 'number', nullable: true },
            exception_reason: { type: 'string', nullable: true },
            exception_authorized_by: { type: 'integer', nullable: true },
            client_op_id: { type: 'string', nullable: true },
            notes: { type: 'string', nullable: true },
            details: {
              type: 'array',
              items: { $ref: '#/components/schemas/DeliveryDetail' },
            },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        DistributionPlan: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            plan_code: { type: 'string' },
            created_by: { type: 'integer' },
            status: {
              type: 'string',
              enum: ['PROGRAMADA', 'EN_EJECUCION', 'COMPLETADA', 'CANCELADA'],
            },
            scope: { type: 'string', enum: ['GLOBAL', 'ZONA', 'REFUGIO', 'LOTE'] },
            scope_id: { type: 'integer', nullable: true },
            notes: { type: 'string', nullable: true },
            items_total: { type: 'integer' },
            items_pendientes: { type: 'integer' },
            items_entregados: { type: 'integer' },
            items_sin_atender: { type: 'integer' },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        DistributionPlanItem: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            plan_id: { type: 'integer' },
            family_id: { type: 'integer' },
            source_warehouse_id: { type: 'integer', nullable: true },
            target_coverage_days: { type: 'integer' },
            priority_score_snapshot: { type: 'number' },
            status: {
              type: 'string',
              enum: ['PENDIENTE', 'ENTREGADO', 'SIN_ATENDER'],
            },
            delivery_id: { type: 'integer', nullable: true },
            reason: { type: 'string', nullable: true },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        HealthVector: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            vector_type: {
              type: 'string',
              enum: ['AGUA_CONTAMINADA', 'INSECTOS', 'ROEDORES', 'OTRO'],
            },
            risk_level: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] },
            status: { type: 'string', enum: ['ACTIVO', 'EN_ATENCION', 'RESUELTO'] },
            description: { type: 'string', nullable: true },
            actions_taken: { type: 'string', nullable: true },
            latitude: { type: 'number', nullable: true },
            longitude: { type: 'number', nullable: true },
            zone_id: { type: 'integer', nullable: true },
            shelter_id: { type: 'integer', nullable: true },
            reported_date: { type: 'string', format: 'date-time' },
            reported_by: { type: 'integer' },
            resolved_at: { type: 'string', format: 'date-time', nullable: true },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        Relocation: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            family_id: { type: 'integer' },
            origin_shelter_id: { type: 'integer', nullable: true },
            destination_shelter_id: { type: 'integer' },
            type: { type: 'string', enum: ['TEMPORARY', 'PERMANENT'] },
            relocation_date: { type: 'string', format: 'date-time' },
            reason: { type: 'string' },
            authorized_by: { type: 'integer' },
            notes: { type: 'string', nullable: true },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        AuditLog: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            action: { type: 'string' },
            module: { type: 'string' },
            entity: { type: 'string' },
            entity_id: { type: 'integer', nullable: true },
            user_id: { type: 'integer', nullable: true },
            before: { type: 'object', nullable: true },
            after: { type: 'object', nullable: true },
            ip_address: { type: 'string', nullable: true },
            user_agent: { type: 'string', nullable: true },
            created_at: { type: 'string', format: 'date-time' },
          },
        },
      },
      responses: {
        Unauthorized: {
          description: 'Token ausente o inválido',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: { success: false, error: 'Token requerido' },
            },
          },
        },
        Forbidden: {
          description: 'El rol del usuario no tiene permiso para esta acción',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: { success: false, error: 'Acceso denegado' },
            },
          },
        },
        NotFound: {
          description: 'Recurso no encontrado',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: { success: false, error: 'Recurso no encontrado' },
            },
          },
        },
        Conflict: {
          description: 'Conflicto de datos (duplicado, estado inválido)',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: { success: false, error: 'El recurso ya existe' },
            },
          },
        },
        ValidationError: {
          description: 'Errores de validación en el cuerpo o parámetros',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: { success: false, error: 'email debe ser un email válido' },
            },
          },
        },
        Locked: {
          description: 'Cuenta bloqueada temporalmente por intentos fallidos',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: { success: false, error: 'Cuenta bloqueada. Intente más tarde.' },
            },
          },
        },
      },
    },
    security: [{ bearerAuth: [] }],
  },
  apis: [
    path.join(__dirname, '../routes/*.ts'),
    path.join(__dirname, '../controllers/*.ts'),
  ],
};

export const swaggerSpec = swaggerJsdoc(options);
